import { Container, Heading } from "@chakra-ui/layout";
import { Box, Button, Flex } from "@chakra-ui/react";
import axios from "axios";
import { isEmpty } from "lodash";
import { GetServerSideProps } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import ReactDiffViewer from "react-diff-viewer";
import { Layout, NextChakraLink } from "../../components";
import { WikiPageArchive, WikiPageProps } from "../../types";
import { API_ENDPOINTS } from "../../utils";

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { slug, archiveId } = context.query;

  if (
    !context.query ||
    typeof slug !== "string" ||
    typeof archiveId !== "string"
  ) {
    return {
      props: {
        data: { notFound: true } as WikiPageProps,
      },
    };
  }

  const { data } = await axios.get(
    `${API_ENDPOINTS.BASE_URL}/${API_ENDPOINTS.GET_ARCHIVE}`,
    {
      params: {
        slug,
        archiveId,
      },
    },
  );

  return {
    props: {
      data: isEmpty(data) ? ({ notFound: true } as WikiPageProps) : data,
    },
  };
};

const DiffPage = ({ data }: { data: WikiPageArchive }) => {
  const {
    notFound,
    archiveDate,
    id,
    slug,
    title,
    content,
    description,
    sourcePage,
  } = data;
  const router = useRouter();

  const goBack = () => {
    router.back();
  };

  return (
    <div>
      <Head>
        <title>Simple Wiki Engine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Container maxWidth="container.lg" mt="8">
          <Flex
            pt="8"
            px="16"
            alignItems="center"
            justifyContent={title ? `space-between` : `flex-end`}
          >
            {title && <Heading as="h2">{title}</Heading>}

            <Box fontWeight="medium">
              <Button
                onClick={() => goBack()}
                variant="link"
                color="blue"
                mr="6"
              >
                Go Back
              </Button>
              {!notFound && (
                <NextChakraLink href={`/wiki/${slug}`} color="blue">
                  Go to Page
                </NextChakraLink>
              )}
            </Box>
          </Flex>

          {notFound ? (
            <Heading as="h2" textAlign="center">
              Page not found
            </Heading>
          ) : (
            <Box mt="8">
              <ReactDiffViewer
                oldValue={content}
                newValue={sourcePage.content}
                splitView
              />
            </Box>
          )}
        </Container>
      </Layout>
    </div>
  );
};

export default DiffPage;
