import { Button } from "@chakra-ui/button";
import { Box, Container, Flex, Heading, Text } from "@chakra-ui/layout";
import ChakraUIRenderer from "chakra-ui-markdown-renderer";
import { GetServerSideProps } from "next";
import Head from "next/head";
import React from "react";
import ReactMarkdown from "react-markdown";
import { Layout, NextChakraLink } from "../../components";
import MarkdownParser from "../../components/MarkdownParser";
import { WikiPageProps } from "../../types";
import { getPageFromSlug, WIKI_HOME_URL } from "../../utils";

export const getServerSideProps: GetServerSideProps = async (context) => {
  if (!context.params || typeof context.params[`slug`] !== "string") {
    return {
      notFound: true,
    };
  }

  const slug = context.params[`slug`];
  const data = await getPageFromSlug(slug);
  return {
    props: {
      data,
    },
  };
};

const WikiPage = ({
  data: { slug, title, content, notFound },
}: {
  data: WikiPageProps;
}) => {
  return (
    <div>
      <Head>
        <title>Simple Wiki Engine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div>
          <Flex
            pt="8"
            px="16"
            alignItems="center"
            justifyContent="space-between"
          >
            <Heading as="h2">{title || slug}</Heading>

            <Box fontWeight="medium">
              <NextChakraLink href={`/edit-page/${slug}`} color="blue" mr="6">
                {notFound ? `Create Page` : `Edit Page`}
              </NextChakraLink>
              {!notFound && (
                <NextChakraLink href={`/`} color="blue">
                  View History
                </NextChakraLink>
              )}
            </Box>
          </Flex>

          <Container id="page-content" maxW="container.lg" mt="16">
            {notFound ? (
              <>
                <Text fontSize="xl" fontWeight="semibold">
                  This page does not exist yet.
                </Text>
                <Button as={NextChakraLink} href={WIKI_HOME_URL} mt="6">
                  Go home
                </Button>
              </>
            ) : (
              content && (
                <ReactMarkdown
                  components={{
                    ...ChakraUIRenderer(),
                    p: MarkdownParser,
                  }}
                  skipHtml={false}
                >
                  {content}
                </ReactMarkdown>
              )
            )}
          </Container>
        </div>
      </Layout>
    </div>
  );
};

export default WikiPage;
