import { Button } from "@chakra-ui/button";
import { Box, Container, Flex, Heading, Text } from "@chakra-ui/layout";
import ChakraUIRenderer from "chakra-ui-markdown-renderer";
import { GetServerSideProps } from "next";
import Head from "next/head";
import React from "react";
import ReactMarkdown from "react-markdown";
import { Layout, NextChakraLink } from "../../components";
import { WikiPageProps } from "../../types";
import { BASE_URL, WIKI_HOME_URL } from "../../utils";

export const getServerSideProps: GetServerSideProps = async (context) => {
  if (!context.params || typeof context.params[`slug`] !== "string") {
    return {
      notFound: true,
    };
  }

  const slug = context.params[`slug`];

  let data: WikiPageProps = { slug } as any;
  try {
    const res = await fetch(`${BASE_URL}/page/${slug}`);

    if (res.status !== 200) {
      throw new Error(`page not found`);
    }

    data = await res.json();
  } catch (error) {
    data.notFound = true;
    console.error({ wiki_page_error: (error as Error).message });
  }

  return {
    props: {
      data,
    },
  };
};

const WikiPage = ({
  data: { notFound, content, slug, title },
}: {
  data: WikiPageProps;
}) => {
  return (
    <div>
      <Head>
        <title>Simple Wiki Engine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div>
          <Flex
            pt="8"
            px="16"
            alignItems="center"
            justifyContent="space-between"
          >
            <Heading as="h2">{title}</Heading>

            <Box fontWeight="medium">
              <NextChakraLink href={`/edit-page/${slug}`} color="blue" mr="6">
                {notFound ? `Create Page` : `Edit Page`}
              </NextChakraLink>
              {!notFound && (
                <NextChakraLink href={`/`} color="blue">
                  View History
                </NextChakraLink>
              )}
            </Box>
          </Flex>

          <Container id="page-content" maxW="container.lg" mt="16">
            {notFound ? (
              <>
                <Text fontSize="xl" fontWeight="semibold">
                  This page does not exist yet.
                </Text>
                <Button as={NextChakraLink} href={WIKI_HOME_URL} mt="6">
                  Go home
                </Button>
              </>
            ) : (
              <ReactMarkdown components={ChakraUIRenderer()} skipHtml={false}>
                {content}
              </ReactMarkdown>
            )}
          </Container>
        </div>
      </Layout>
    </div>
  );
};

export default WikiPage;
