import { Container, Flex, Heading } from "@chakra-ui/layout";
import ChakraUIRenderer from "chakra-ui-markdown-renderer";
import { GetServerSideProps } from "next";
import Head from "next/head";
import React from "react";
import ReactMarkdown from "react-markdown";
import { Layout, NextChakraLink } from "../../components";
import { BASE_URL, postData } from "../../utils";

const sampleMarkdown = `
## express.js hello world example

\`\`\`js
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
  res.send('Hello World!')
})

app.listen(port, () => {
  console.log(\`Example app listening at http://localhost:\${port}\`)
})
\`\`\`

[Test Link](/foo)
`;

type PageProps = {
  slug: string;
  title: string;
  description?: string;
  content: string; // markdown
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  if (!context.params || typeof context.params["slug"] !== "string") {
    return {
      notFound: true,
    };
  }

  const slug = context.params["slug"];

  try {
    const res = await fetch(`${BASE_URL}/get-page/${slug}`).then((res) =>
      res.json(),
    );
  } catch (error) {}

  return {
    props: {
      data: {},
    },
  };
};

const WikiPage = ({ data }: { data: PageProps }) => {
  return (
    <div>
      <Head>
        <title>Simple Wiki Engine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div>
          <Flex
            pt="8"
            px="16"
            alignItems="center"
            justifyContent="space-between"
          >
            <Heading as="h2">{data.slug}</Heading>

            <Flex fontWeight="medium">
              <NextChakraLink href={`/`} color="blue" mr="6">
                Edit Page
              </NextChakraLink>
              <NextChakraLink href={`/`} color="blue">
                View History
              </NextChakraLink>
            </Flex>
          </Flex>

          <Container id="markdown-content" maxW="container.lg" mt="16">
            <ReactMarkdown components={ChakraUIRenderer()} skipHtml={false}>
              {sampleMarkdown}
            </ReactMarkdown>
          </Container>
        </div>
      </Layout>
    </div>
  );
};

export default WikiPage;
