import type { NextPage } from "next";
import Head from "next/head";
import router from "next/router";
import { Layout } from "../components";
import { WIKI_HOME_URL } from "../utils";

const Home: NextPage = () => {
  router.replace(WIKI_HOME_URL);

  return (
    <div>
      <Head>
        <title>Simple Wiki Engine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout></Layout>
    </div>
  );
};

export default Home;
