import {
  Container,
  Heading,
  Table,
  TableCaption,
  Tbody,
  Td,
  Th,
  Thead,
  Tr,
} from "@chakra-ui/react";
import axios from "axios";
import { GetServerSideProps } from "next";
import Head from "next/head";
import React from "react";
import { Layout, NextChakraLink } from "../../components";
import { WikiPageProps } from "../../types";
import { API_ENDPOINTS } from "../../utils";

export const getServerSideProps: GetServerSideProps = async (context) => {
  if (!context.query || typeof context.query[`text`] !== "string") {
    return {
      props: {
        data: [],
      },
    };
  }

  const text = context.query[`text`];
  const { data: pages } = await axios.get(
    `${API_ENDPOINTS.BASE_URL}/${API_ENDPOINTS.SEARCH_PAGE}`,
    {
      params: { text },
    },
  );

  return {
    props: {
      data: {
        text: text || "",
        pages,
      },
    },
  };
};

const SearchPage = ({
  data: { pages, text },
}: {
  data: { text: string; pages: WikiPageProps[] };
}) => {
  return (
    <div>
      <Head>
        <title>Simple Wiki Engine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Container maxWidth="container.lg" mt="8">
          {pages && text && (
            <Heading as="h2">
              {text} Search Results: {pages.length}
            </Heading>
          )}

          <Table
            variant="simple"
            size="lg"
            colorScheme="gray"
            border="1px"
            borderColor="gray.200"
            mt="8"
          >
            <TableCaption>Page Search Results</TableCaption>
            <Thead>
              <Tr>
                <Th>Page Title</Th>
                <Th>Content</Th>
                <Th>Link</Th>
              </Tr>
            </Thead>
            <Tbody>
              {pages.map((page) => (
                <Tr key={page.slug}>
                  <Td>{page.title}</Td>
                  <Td>{page.content}</Td>
                  <Td>
                    <NextChakraLink
                      href={`/wiki/${page.slug}`}
                      fontWeight="semibold"
                    >
                      Link
                    </NextChakraLink>
                  </Td>
                </Tr>
              ))}
            </Tbody>
          </Table>
        </Container>
      </Layout>
    </div>
  );
};

export default SearchPage;
