import { Heading } from "@chakra-ui/layout";
import { GetServerSideProps } from "next";
import Head from "next/head";
import React from "react";
import { Layout } from "../../components";

type PageProps = {};

export const getServerSideProps: GetServerSideProps = async (context) => {
  if (!context.params || typeof context.params["slug"] !== "string") {
    return {
      notFound: true,
    };
  }

  const slug = context.params["slug"];

  let data: PageProps = { slug } as any;

  return {
    props: {
      data,
    },
  };
};

const EditPage = ({ data }: { data: PageProps }) => {
  return (
    <div>
      <Head>
        <title>Simple Wiki Engine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Heading as="h2" mt="6" textAlign="center">
          Edit Page 🚧
        </Heading>
      </Layout>
    </div>
  );
};

export default EditPage;
